Ajudai/AjudaiWeb/Controllers/ChamadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ajudai.Modelo;
using Ajudai.DAL;

namespace AjudaiWeb.Controllers
{
    [Authorize]
    [AccessSessions]
    public class ChamadoController : Controller
    {
        ChamadoDAO chamado = new ChamadoDAO();
        ProdutoDAO produtos = new ProdutoDAO();

        //Abrir Chamado
        public ActionResult AbrirChamado()
        {
            ViewBag.ListarProdutos = new SelectList(produtos.ddListarProdutos().Select(p => new SelectListItem
            {
                Value = p.id.ToString(),
                Text = p.nome + " - " + p.descricao
            }), "Value", "Text");

            return View();
        }

        //Abrir Chamado - post
        [HttpPost]
        public ActionResult AbrirChamado(ddChamado dadosTela)
        {
            dadosTela.idCliente = Convert.ToInt32(Session["ssCodUsuario"]);
            dadosTela.idFuncionario = 1;//código fixo do administrador, este receberá o chamado
            dadosTela.txStatus = "Aberto";//status pendente
            chamado.CadastrarChamado(dadosTela);

            TempData.Add("Mensagem-Sucesso", "Chamado aberto com sucesso");
            return RedirectToAction("Index", "Cliente");
        }

        //Consultar o chamado
        public ActionResult ConsultarChamado(int cdChamado)
        {
            ddChamado dadosChamado = new ddChamado();

            dadosChamado = chamado.PesquisarChamadoPorId(cdChamado);
            
            return View(dadosChamado);
        }

        //grava o posicionamento do cliente
        [HttpPost]
        public ActionResult CadastrarPosicionamento(ddChamado dadosTela)
        {
            chamado.CadastrarPosicionamentoCliente(dadosTela);

            TempData.Add("Mensagem-Sucesso", "Posicionamento salvo com sucesso");
            return RedirectToAction("ConsultarChamado", new { cdChamado = dadosTela.id });
        }

        //grava a avaliação
        [HttpPost]
        public ActionResult CadastrarAvaliacao(ddChamado dadosTela)
        {
            chamado.CadastrarAvaliacao(dadosTela);

            TempData.Add("Mensagem-Sucesso", "Avaliado com sucesso");
            return RedirectToAction("ConsultarChamado", new { cdChamado = dadosTela.id });
        }
    }
}

Ajudai/AjudaiWeb/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ajudai.Modelo;
using Ajudai.DAL;

namespace AjudaiWeb.Controllers
{    
    [Authorize]
    [AccessSessions]
    public class ClienteController : Controller
    {
        //Área do Cliente Index
        public ActionResult Index()
        {
            ddCliente cliente = new ddCliente();
            cliente.id = Convert.ToInt32(Session["ssCodUsuario"]);//código do cliente logado

            ClienteDAO chamados = new ClienteDAO();

            List<ddChamado> ListaChamados = chamados.ListarChamadosDoCliente(cliente);

            return View(ListaChamados);
        }

        //Alterar Dados
        public ActionResult AlterarDados()
        {
            return View();
        }
    }
}

Ajudai/AjudaiWeb/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ajudai.Modelo;
using Ajudai.DAL;
using System.Web.Security;

namespace AjudaiWeb.Controllers
{
    public class LoginController : Controller
    {
        //Login
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Cliente");
            }
            return View();
        }

        //Login - post
        [HttpPost]
        public ActionResult Index(ddCliente dadosTela)
        {
            bool valido = false;
            ddCliente novoCliente = new ddCliente();
            ClienteDAO cliente = new ClienteDAO();

            if (cliente.Acessar(dadosTela))
            {
                ddCliente dadosCliente = new ddCliente();
                dadosCliente.login = dadosTela.login;

                novoCliente = cliente.PesquisarClientePorLogin(dadosCliente);

                if (novoCliente.id != 0)
                {
                    valido = true;
                }
            }

            if (valido == true)
            {
                FormsAuthentication.SetAuthCookie(novoCliente.login, true);
                Session.Add("ssCodUsuario", novoCliente.id);
                Session.Add("ssLogin", novoCliente.login);                
                return RedirectToAction("Index", "Cliente");
            }
            else
            {
                TempData.Add("Mensagem-Erro", "Usuário e/ou senha inválido(s). Tente novamente.");
                return RedirectToAction("Index");
            }
        }

        //Cadastro
        public ActionResult Cadastro()
        {
            return View();
        }

        //Cadastro - post
        [HttpPost]
        public ActionResult Cadastro(ddCliente dadosTela)
        {
            ClienteDAO cliente = new ClienteDAO();
            if (ModelState.IsValid)
            {
                cliente.CadastrarCliente(dadosTela);
                TempData.Add("Mensagem-Sucesso", "Cadastrado com sucesso!");
                return RedirectToAction("Cadastro");
            }
            else
            {
                return View(dadosTela);
            }            
        }

        //Sair
        public ActionResult Sair()
        {
            FormsAuthentication.SignOut();
            Session.RemoveAll();
            TempData.Add("Mensagem-Sucesso", "Sessão encerrada com sucesso!! Até breve.");
            return RedirectToAction("Index");
        }
    }
}

Ajudai/AjudaiWeb/Views/Chamado/AbrirChamado.cshtml
@model Ajudai.Modelo.ddChamado
@{
    ViewBag.Title = "Abrir Chamado";
    Layout = "~/Views/Shared/_LayoutPageClient.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-12 pt-3 mb-2">
            <h1 class="form-check h2 ">Abrir Chamado</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 pb-3 ">
            <p class="lead">Descreva sua solicitação abaixo.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 pb-5">
            @using (Html.BeginForm("AbrirChamado", "Chamado", FormMethod.Post))
            {
                <div class="row">
                    <div class="col-md-12 mb-3">
                        <label>Produto</label>
                        @Html.DropDownListFor(x => x.idProduto, ViewBag.ListarProdutos as SelectList, new { @class = "form-control" })
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 mb-3">
                        <label>Descrição do chamado</label>
                        @Html.TextAreaFor(x => x.descricao, new { @class = "form-control", rows = "5" })
                        @Html.ValidationMessageFor(model => model.descricao, "", new { @class = "text-danger" })
                    </div>
                </div>
                <button class="btn btn-success btn-lg px-5" type="submit">Salvar</button>
            }
        </div>
    </div>
    <footer class="fixed-bottom col-md-12 mb-5">
        <div class="form-row">
            <div class="col-md-12 mt-2">
                <a href="~/Cliente" class="btn btn-outline-dark btn-sm px-5">Voltar</a>
            </div>
        </div>
    </footer>
</div>

Ajudai/AjudaiWeb/Views/Chamado/ConsultarChamado.cshtml
@model Ajudai.Modelo.ddChamado
@{
    ViewBag.Title = "Consultar Chamado";
    Layout = "~/Views/Shared/_LayoutPageClient.cshtml";
}
<div class="container">
    <div class="row text-center">
        <div class="col-md-12 pt-3 mb-3">
            <h1 class="form-check h2 ">Consultar Chamado</h1>
        </div>
    </div>
    <div class="row text-center">
        <div class="col-md-12 pb-2 mb-3">
            <p class="lead">Consulte os detalhes do seu chamado abaixo.</p>
        </div>
    </div>
    <form class="text-center bg-info mb-3">
        <div class="form-row align-items-center">
            <div class="col-md-4 mb-3">
                <label>Produto</label><br />
                @Model.Produto.nome - @Model.Produto.descricao
            </div>
            <div class="col-md-4 mb-3">
                <label>Data de Abertura</label><br />
                @Model.dtAbertura
            </div>
            <div class="col-md-4 mb-3">
                <label>Status</label><br />
                @if (Model.txStatus == "Aberto")
                {
                    <span class="text-danger table-dark">Aberto</span>
                }
                else
                if (Model.txStatus == "Em atendimento")
                {
                    <span class="text-warning table-dark">Em Atendimento</span>
                }
                else
                if (Model.txStatus == "Concluído")
                {
                    <span class="text-success table-dark">Concluído</span>
                }
            </div>
        </div>

        <div class="form-row align-items-center">
            <div class="col-md-4 mb-3">
                <label>Descrição do chamado</label><br />
                @Model.descricao
            </div>

            @{
                if (Model.txStatus == "Em atendimento" || Model.txStatus == "Concluído")
                {
                    <div class="col-md-4 mb-3">
                        <label>Posicionamento do funcionário</label><br />
                        @Model.posicionamentoFuncionario
                    </div>

                    <div class="col-md-4 mb-3">
                        <label>Posicionamento do cliente</label><br />
                        @Model.posicionamentoCliente
                    </div>
                }
            }
        </div>
        @{
            if (Model.txStatus == "Concluído")
            {
                <div class="form-row align-items-center">
                    <div class="col-md-4 mb-3">
                        <label>Solução</label><br />
                        @Model.solucao
                    </div>
                    @{
                        if (Model.avaliacao != " ")
                        {
                            <div class="col-md-4 mb-3">
                                <label>Avaliação</label><br />
                                @Model.avaliacao
                            </div>
                        }
                    }
                </div>
            }
        }
    </form>
    @{
        if (Model.txStatus == "Em atendimento" && Model.posicionamentoCliente == " ")
        {
            using (Html.BeginForm("CadastrarPosicionamento", "Chamado", FormMethod.Post))
            {
                @Html.HiddenFor(x => x.id)
                <div class="form-row text-center">
                    <div class="col-md-12 mb-3">
                        <label>Editar posicionamento</label><br />
                        @Html.TextAreaFor(x => x.posicionamentoCliente, new { @class = "form-control", rows = "3" })
                    </div>
                    <div class="col-md-12 mt-2">
                        <button type="submit" class="btn btn-success btn-sm px-5">Salvar</button>
                    </div>
                </div>
            }
        }

        if (Model.txStatus == "Concluído" && Model.avaliacao == " ")
        {
            using (Html.BeginForm("CadastrarAvaliacao", "Chamado", FormMethod.Post))
            {
                @Html.HiddenFor(x => x.id)
                <div class="form-row text-center">
                    <div class="col-md-12 mb-3">
                        <label>Avaliar atendimento</label><br />
                        @Html.DropDownListFor(x => x.avaliacao, new SelectList
                                                (new List<Object>
                                                    {
                                                      new {value = 1, text = "Péssimo" },
                                                      new {value = 2, text = "Ruim" },
                                                      new {value = 3, text = "Regular" },
                                                      new {value = 4, text = "Bom" },
                                                      new {value = 5, text = "Ótimo" }
                                                    }, "value", "text")
                                                )
                    </div>
                    <div class="col-md-12 mt-2">
                        <button type="submit" class="btn btn-success btn-sm px-5">Salvar</button>
                    </div>
                </div>
            }
        }
    }
    <footer class="fixed-bottom col-md-12 mb-5">
        <div class="form-row">
            <div class="col-md-12 mt-2">
                <a href="~/Cliente" class="btn btn-outline-dark btn-sm px-5">Voltar</a>
            </div>
        </div>
    </footer>
</div>

Ajudai/AjudaiWeb/Views/Cliente/AlterarDados.cshtml
@model Ajudai.Modelo.ddCliente
@{
    ViewBag.Title = "AlterarDados";
    Layout = "~/Views/Shared/_LayoutPageClient.cshtml";
}
<div class="container">
    <div class="form-horizontal alert-info col-md-12 mb-5">
        <div class="row">
            <div class="col-md-12 pt-3 mb-3">
                <h1 class="h2">Alterar Senha</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 pb-2 mb-3">
                <p class="lead">Altere sua senha abaixo. Para alterar outros dados abra um chamado.</p>
            </div>
        </div>
    </div>

    <div class="form-horizontal alert-info col-md-12 mb-5 ">
        <div class="col-md-6 mb-5 ">
            <label for="password">Nova senha</label>
            @Html.TextBoxFor(x => x.senha, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.senha, "", new { @class = "text-danger" })
        </div>

        <button class="btn btn-primary btn-md  mb-3" type="submit">Alterar</button>
    </div>
    <footer class="fixed-bottom col-md-12 mb-5">
        <div class="form-row">
            <div class="col-md-12 mt-2">
                <a href="~/Cliente" class="btn btn-outline-dark btn-sm px-5">Voltar</a>
            </div>
        </div>
    </footer>
</div>

Ajudai/AjudaiWeb/Views/Cliente/Index.cshtml
@using Ajudai.Modelo
@model List<ddChamado>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPageClient.cshtml";
}
<div class="accordion mt-2">
    <div class="card-header">
        <h1 class="form-check h2 ">Bem vindo ao Ajuda.í</h1>
        <p>Neste espaço você poderá abrir e acompanhar chamados para nossa equipe.</p>
    </div>
</div>
<div class="container-fluid pt-3 pb-2 mb-3">
    <div class="row">
        <div class="col-6 text-center text-sm-left">
            <h1 class="h4">Meus Chamados</h1>
        </div>
        <div class="col-6 text-center text-sm-right">
            <a href="@Url.Action("AbrirChamado","Chamado")" class="btn btn-danger">
                <span data-feather="calendar"></span>
                Abrir Chamado
            </a>
        </div>
    </div>
</div>
@if (Model.Count > 0)
{
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th class="text-center">ID</th>
                    <th>Produto</th>
                    <th class="text-center">Data</th>
                    <th class="text-center">Status</th>
                    <th class="text-center">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var chamado in Model)
                {
                    <tr>
                        <td class="text-center">@chamado.id</td>
                        <td>@chamado.Produto.nome</td>
                        <td class="text-center">@chamado.dtAbertura</td>
                        <td class="text-center">
                            @if (chamado.txStatus == "Aberto")
                            {
                                <span class="text-danger table-dark">Aberto</span>
                            }
                            else
                            if (chamado.txStatus == "Em atendimento")
                            {
                                <span class="text-warning table-dark">Em Atendimento</span>
                            }
                            else
                            if (chamado.txStatus == "Concluído")
                            {
                                <span class="text-success table-dark">Concluído</span>
                            }
                        </td>
                        <td class="text-center">
                            <a href="@Url.Action("ConsultarChamado","Chamado", new { cdChamado = chamado.id })" class="btn btn-sm btn-primary">
                                Consultar
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="container-fluid pt-3 pb-2 mb-3">
        <div class="row">
            <div class="col-12 text-center">
                <div class="alert alert-danger">
                    Nenhum chamado encontrado
                </div>
            </div>
        </div>
    </div>
}

Ajudai/AjudaiWeb/Views/DadosCliente/Cadastro.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cadastro</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

Ajudai/AjudaiWeb/Views/Login/Cadastro.cshtml
@model Ajudai.Modelo.ddCliente
@{
    ViewBag.Title = "Cadastro";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<div class="container">
    <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src="/Content/images/logo.jpeg" alt="" height="72">
        <h2>Cadastro de cliente</h2>
        <p class="lead">Preencha os campos abaixo para poder utilizar nosso sistema de chamados.</p>
    </div>

    <div class="form-horizontal alert-info col-md-12 mb-5">
        <div class="col-md-12 order-md-1">
            @using (Html.BeginForm("Cadastro", "Login", FormMethod.Post))
            {

                <div class="col-md-12">
                    <h4 class="mb-3">1. Dados Pessoais</h4>
                </div>

                <div class="row">
                    <div class="col-md-12 mb-3">
                        <label for="firstName">Nome Completo</label>
                        @Html.TextBoxFor(x => x.nome, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 mb-3">
                        <label for="lastName">E-mail</label>
                        @Html.TextBoxFor(x => x.email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="lastName">Telefone Fixo</label>
                        @Html.TextBoxFor(x => x.telefone, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.telefone, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="lastName">Telefone Celular</label>
                        @Html.TextBoxFor(x => x.celular, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.celular, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="lastName">CEP</label>
                        @Html.TextBoxFor(x => x.cep, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.cep, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="lastName">Endereço</label>
                        @Html.TextBoxFor(x => x.endereco, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.endereco, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6 mb-3">
                        <label for="lastName">Cidade</label>
                        @Html.TextBoxFor(x => x.cidade, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.cidade, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="lastName">UF</label>
                        @Html.TextBoxFor(x => x.uf, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.uf, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-12">
                    <h4 class="mb-3">2. Dados de Acesso</h4>
                </div>

                <div class="row mb-5">
                    <div class="col-md-6 mb-3">
                        <label for="firstName">Login</label>
                        @Html.TextBoxFor(x => x.login, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.login, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="password">Senha</label>
                        @Html.TextBoxFor(x => x.senha, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.senha, "", new { @class = "text-danger" })
                    </div>
                </div>

                <button class="btn btn-primary btn-lg mb-3 " type="submit">Cadastrar</button>
            }
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 text-left mt-5">
            <a href="~/Login" class="btn btn-outline-secondary">Voltar para login</a>
        </div>
    </div>
    <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">&copy; 2017-2018 UniDev</p>
    </footer>
</div>

Ajudai/AjudaiWeb/Views/Login/Index.cshtml
@model Ajudai.Modelo.ddCliente

@{
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<link href="~/Content/signin.css" rel="stylesheet" />


@using (Html.BeginForm("Index", "Login", FormMethod.Post, new { @class = "form-signin" }))
{
    <img class="d-block mx-auto mb-4" src="/Content/images/logo.jpeg" alt="" height="72">
    <h1 class="h3 mb-3 font-weight-normal text-center">Minha Área</h1>
    @Html.LabelFor(x => x.login, new { @class = "sr-only" })
    @Html.TextBoxFor(x => x.login, new { @class = "form-control", placeholder = "Usuário", required = "required", autofocus = "autofocus" })
    @Html.LabelFor(x => x.senha, new { @class = "sr-only" })
    @Html.PasswordFor(x => x.senha, new { @class = "form-control", placeholder = "Senha", required = "required" })
    <button class="btn btn-lg btn-primary btn-block" type="submit">Acessar</button>
    <a href="~/Login/Cadastro" class="btn btn-lg btn-danger btn-block">Ainda não tenho cadastro</a>
    <p class="my-4 text-muted text-center">&copy; 2017-2018 UniDev</p>
}

Ajudai/AjudaiWeb/Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Ajuda.í</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/styles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.0.0.slim.js"></script>
</head>
<body>
    @if (TempData["Mensagem-Erro"] != null || TempData["Mensagem-Sucesso"] != null)
    {
        @Html.Partial("_PartialMensagem");
    }
    @RenderBody()
    
    <script src="~/Scripts/umd/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Ajudai/AjudaiWeb/Views/Shared/_LayoutPageClient.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Ajuda.í</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/styles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.0.0.slim.js"></script>
</head>
<body>
    @if (TempData["Mensagem-Erro"] != null || TempData["Mensagem-Sucesso"] != null)
    {
        @Html.Partial("_PartialMensagem");
    }
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
        <a class="navbar-brand mr-5" href="@Url.Action("Index","Cliente")">Ajuda.í</a>
        <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mr-2">
                    <a class="nav-link" href="@Url.Action("Index","Cliente")">Meus Chamados</a>
                </li>
                <li class="nav-item mr-2">
                    <a class="nav-link" href="@Url.Action("AbrirChamado","Chamado")">Abrir Chamado</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("AlterarDados","Cliente")">Alterar Senha</a>
                </li>
            </ul>
            <div class="ml-auto mr-3 text-light">
                Olá <strong>@Session["ssLogin"]</strong>
            </div>
            <a class="btn btn-light my-2 my-sm-0" href="@Url.Action("Sair","Login")">Sair</a>
        </div>
    </nav>

    <main role="main" class="container-fluid">
        @RenderBody()
    </main>
    
    <script src="~/Scripts/umd/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/offcanvas.js"></script>
</body>
</html>

Ajudai/AjudaiWeb/Views/Shared/_PartialMensagem.cshtml
@if (TempData["Mensagem-Sucesso"] != null)
{
    <script>
        $(document).ready(function () {
            $('.modal-alert').modal('show');
            setTimeout(function () { $('.modal-alert').modal('hide') }, 5000);
        });
    </script>

    <div class="modal fade modal-alert">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content bg-success">
                <div class="modal-header p-b-0" style="border-bottom:none">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body pb-5 pt-0">
                    <div class="modal-body text-light">
                        <div class="row">
                            <div class="col-lg-12 text-center">
                                <h5>@Html.Raw(TempData["Mensagem-Sucesso"])</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@if (TempData["Mensagem-Erro"] != null)
{
    <script>
    $(document).ready(function () {
        $('.modal-alert').modal('show');
        setTimeout(function () { $('.modal-alert').modal('hide') }, 5000);
    });
    </script>

    <div class="modal fade modal-alert">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content bg-danger">
                <div class="modal-header p-b-0" style="border-bottom:none">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body pb-5 pt-0">
                    <div class="modal-body text-light">
                        <div class="row">
                            <div class="col-lg-12 text-center">
                                <h5>@Html.Raw(TempData["Mensagem-Erro"])</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}